/** @type {import('tailwindcss').Config} */
// Design tokens extracted verbatim from the Stitch export (Google Material 3 style
// token set) so every generated page matches the original UI exactly.
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary-container": "#86a0cd",
        "surface-dim": "#d7dadc",
        "on-secondary-fixed": "#2b1700",
        "on-error": "#ffffff",
        "tertiary-fixed": "#a5eff0",
        "primary-fixed-dim": "#adc7f7",
        "primary": "#002045",
        "tertiary-container": "#003d3e",
        "error-container": "#ffdad6",
        "tertiary-fixed-dim": "#89d3d4",
        "on-error-container": "#93000a",
        "error": "#ba1a1a",
        "on-tertiary": "#ffffff",
        "surface": "#f7fafc",
        "on-secondary-fixed-variant": "#673d00",
        "tertiary": "#002526",
        "on-primary-fixed-variant": "#2d476f",
        "primary-fixed": "#d6e3ff",
        "background": "#f7fafc",
        "primary-container": "#1a365d",
        "surface-container-low": "#f1f4f6",
        "surface-variant": "#e0e3e5",
        "surface-tint": "#455f88",
        "outline": "#74777f",
        "inverse-primary": "#adc7f7",
        "on-tertiary-fixed": "#002020",
        "on-surface": "#181c1e",
        "on-surface-variant": "#43474e",
        "surface-bright": "#f7fafc",
        "on-primary-fixed": "#001b3c",
        "on-secondary-container": "#744600",
        "surface-container-highest": "#e0e3e5",
        "secondary-fixed": "#ffddba",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#eef1f3",
        "on-tertiary-container": "#61abac",
        "surface-container": "#ebeef0",
        "on-background": "#181c1e",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#004f50",
        "on-secondary": "#ffffff",
        "secondary": "#875200",
        "surface-container-high": "#e5e9eb",
        "secondary-fixed-dim": "#ffb866",
        "secondary-container": "#ffb55c",
        "inverse-surface": "#2d3133",
        "outline-variant": "#c4c6cf",

        // --- Added for the booking flow (Figma: "Urban Company practice file") ---
        // Kept as a separate, additively-named token set so nothing above this
        // line (the original Stitch/SevaSetu tokens) is touched.
        "brand-purple": "#7E57C2",
        "brand-purple-dark": "#5E35B1",
        "brand-purple-light": "#F3EEFC",
        "brand-orange": "#F5A623",
        "brand-success": "#1DB954",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        md: "16px",
        xl: "48px",
        "margin-mobile": "16px",
        base: "4px",
        sm: "8px",
        lg: "24px",
        "margin-desktop": "64px",
        gutter: "16px",
      },
      fontFamily: {
        "display-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "status-badge": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
      },
      fontSize: {
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "status-badge": ["12px", { lineHeight: "16px", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
