import { useEffect, useState } from "react";
import workerService from "../services/workerService";
import Input from "../components/Input";
import Button from "../components/Button";
import Badge from "../components/Badge";
import { LoadingState, ErrorBanner } from "../components/Feedback";

const SKILLS = ["electrician","plumber","carpenter","painter","mason","labour","cleaner","gardener","ac_technician","bazaar_assistant","shopping_companion","driver","caregiver","technician"];

export default function WorkerProfile() {
  const [worker,setWorker]=useState(null); const [form,setForm]=useState(null); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState(""); const [error,setError]=useState("");
  const load=async()=>{try{const r=await workerService.getProfile(); const w=r.data.worker; setWorker(w); setForm({address:w.address||"",city:w.city||"",state:w.state||"",pincode:w.pincode||"",experienceYears:w.experienceYears||0,bio:w.bio||"",skills:w.skills||[],status:w.status||"OFFLINE"});}catch(e){setError(e.response?.data?.message||"Could not load profile");}finally{setLoading(false);}};
  useEffect(()=>{load();},[]);
  const set=(k)=>(e)=>setForm({...form,[k]:e.target.value});
  const toggle=(skill)=>setForm({...form,skills:form.skills.includes(skill)?form.skills.filter(x=>x!==skill):[...form.skills,skill]});
  const save=async(e)=>{e.preventDefault();setSaving(true);setMessage("");setError("");try{const r=await workerService.updateProfile({...form,experienceYears:Number(form.experienceYears)||0});setWorker(r.data.worker);setMessage("Profile updated successfully.");}catch(e){setError(e.response?.data?.message||"Could not update profile");}finally{setSaving(false);}};
  if(loading)return <LoadingState label="Loading your profile…"/>; if(!form)return <ErrorBanner message={error}/>;
  return <div className="max-w-4xl flex flex-col gap-lg"><div><p className="font-status-badge text-status-badge text-primary font-bold">WORKER PROFILE</p><h1 className="font-headline-lg text-headline-lg text-on-surface">Build your professional profile</h1><p className="text-on-surface-variant mt-xs">Keep your skills and experience up to date. Admin approval controls when customers can see you.</p></div><ErrorBanner message={error}/>{message&&<div className="p-md rounded-lg bg-primary-container text-on-primary-container">{message}</div>}
    <div className="bg-surface-container-lowest border border-outline-variant rounded-xl p-lg flex flex-col sm:flex-row sm:items-center gap-md"><div className="w-16 h-16 rounded-full bg-primary-container flex items-center justify-center"><span className="material-symbols-outlined text-primary text-3xl">person</span></div><div className="flex-1"><h2 className="font-headline-md text-headline-md">{worker.user?.name}</h2><p className="text-sm text-on-surface-variant">{worker.user?.email} · {worker.user?.phone}</p></div><Badge tone={worker.verificationStatus === "VERIFIED" ? "verified" : worker.verificationStatus === "REJECTED" ? "rejected" : "pending"}>{worker.verificationStatus}</Badge></div>
    <form onSubmit={save} className="bg-surface-container-lowest border border-outline-variant rounded-xl p-lg flex flex-col gap-md"><h2 className="font-headline-md text-headline-md">Professional details</h2><div className="grid grid-cols-1 md:grid-cols-2 gap-md"><Input label="Experience (years)" type="number" min="0" value={form.experienceYears} onChange={set("experienceYears")}/><div><label className="font-label-md text-label-md text-on-surface block mb-xs">Availability</label><select value={form.status} onChange={set("status")} className="w-full rounded-lg border border-outline-variant bg-surface px-md py-[12px]"><option>AVAILABLE</option><option>BUSY</option><option>OFFLINE</option></select></div></div><Input label="Address" value={form.address} onChange={set("address")}/><div className="grid grid-cols-1 md:grid-cols-3 gap-md"><Input label="City" value={form.city} onChange={set("city")}/><Input label="State" value={form.state} onChange={set("state")}/><Input label="Pincode" value={form.pincode} onChange={set("pincode")}/></div><div><label className="font-label-md text-label-md text-on-surface block mb-xs">Skills</label><div className="flex flex-wrap gap-xs">{SKILLS.map(s=><button type="button" key={s} onClick={()=>toggle(s)} className={`px-sm py-xs rounded-full border text-sm capitalize ${form.skills.includes(s)?"bg-primary-container border-primary text-on-primary-container":"border-outline-variant text-on-surface-variant"}`}>{s.replaceAll("_"," ")}</button>)}</div></div><div><label className="font-label-md text-label-md text-on-surface block mb-xs">About you</label><textarea rows="4" maxLength="500" value={form.bio} onChange={set("bio")} placeholder="Tell customers about your experience and work quality…" className="w-full rounded-lg border border-outline-variant bg-surface px-md py-sm resize-none"/></div><div className="flex justify-end"><Button type="submit" loading={saving}>Save Profile</Button></div></form>
  </div>;
}
